apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-app-monitor
  labels:
    Release: monitoring
spec:
  selector:
    matchLabels:
      app: todo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
